[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
royalty_distribution = "3MoZNBwy5WaRDj3E1QZxq4Wub85smJntJSWdtdtcCBzi"

[programs.devnet]
royalty_distribution = "3MoZNBwy5WaRDj3E1QZxq4Wub85smJntJSWdtdtcCBzi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
